set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(CMAKE_SYSROOT $ENV{TARGET_ROOTFS})
set(CMAKE_STAGING_PREFIX /usr/)

set(CMAKE_C_COMPILER $ENV{CROSS_COMPILE}gcc)
set(CMAKE_CXX_COMPILER $ENV{CROSS_COMPILE}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")
set(
    CMAKE_CUDA_FLAGS
    ${CMAKE_NVCC_FLAGS}
    "-ccbin ${CMAKE_CXX_COMPILER}"
)